enhanced battery monitor util. Read the comments inside

diff --git a/bin/omarchy-battery-monitor b/bin/omarchy-battery-monitor
--- a/bin/omarchy-battery-monitor
+++ b/bin/omarchy-battery-monitor
@@ -2,14 +2,18 @@
 
 # tayowrld for omarchy-mac
 # value is approximate, but close to real one.
-# Sometimes differs from the waybar's value, because of using upower
-# -3 from upower value is to get closer to waybar value
+# Sometimes differs from the waybar's value
+# ignoring it, using bare upower's output
 # due to fast discharging treshold was set to 15%
 #
 # changed:
 # - using upower -b instead of previous logic, gave empty results
+# - added additional notifications percent-to-percent (less than 6%)
 # - added echo on else to test when running command from terminal
 # - exec-once on hyprland instead of systemd timer, then while true cycle
+
+# practice to exit on fail of while true;
+set -o errexit
 
 BATTERY_THRESHOLD=15
 
@@ -26,8 +30,9 @@ get_battery_state() {
 send_notification() {
   notify-send -u critical "󱐋 Time to recharge!" "Battery is down to ${1}%" -i battery-caution -t 30000
 }
+
 while true; do
-  BATTERY_LEVEL=$(($(get_battery_percentage) - 3))
+  BATTERY_LEVEL=$(get_battery_percentage)
   BATTERY_STATE=$(get_battery_state)
 
   if [[ "$BATTERY_STATE" == "discharging" && "$BATTERY_LEVEL" -le "$BATTERY_THRESHOLD" ]]; then
@@ -35,8 +40,20 @@ while true; do
       send_notification "$BATTERY_LEVEL"
       touch "$NOTIFICATION_FLAG"
     fi
+
+    # the logic below:
+    # if the current battery level is equals or less than 5%
+    # and there is no notification flag setted for the current percent
+    # then send a notification and set the custom percent's flag
+    # else ignore and continue, up to the next percent after program and upower refresh
+
+    NOTIFICATION_FLAG_BY_PERCENT="${NOTIFICATION_FLAG}_${BATTERY_LEVEL}"
+    if [[ $BATTERY_LEVEL -le 5 && ! -f "$NOTIFICATION_FLAG_BY_PERCENT" ]]; then
+      send_notification "$BATTERY_LEVEL"
+      touch "$NOTIFICATION_FLAG_BY_PERCENT"
+    fi
   else
-    rm -f "$NOTIFICATION_FLAG"
+    rm -f "${NOTIFICATION_FLAG}" "${NOTIFICATION_FLAG}"_*
     echo "Currently $BATTERY_STATE at $BATTERY_LEVEL%. The threshold to notify is $BATTERY_THRESHOLD% and this utility would notify only on *discharging*"
   fi
 
